export default interface Perfil {
    usuario_id?: number | string,
    nome?: string,
    email?: string,
    cpf?: string,
    cnpj?: string,
    ddi?: string,
    telefone?: string,
    cep?: string,
    logradouro?: string,
    numero?: string,
    unidade?: string,
    complemento?: string,
    cidade?: string,
    estado?: string,
    bairro?: string,
    banco_id?: number,
    nome_banco?: string,
    agencia?: string,
    numero_conta?: string,
    tipo_chave_pix_id?: string,
    tipo_chave_pix?: string,
    pix?: string,
    creci?: string,
    razao_social?: string,
    nome_empresa?: string
}